install:
	yay -S manjaro-pipewire wireplumber helvum pipewire-pulse pipewire-alsa pipewire-jack 
	#pavuctl

link:
	ln -sf /home/Rafa/config/pipewire/config/pipewire ${HOME}/.config/pipewire
	ln -sf /home/Rafa/config/pipewire/config/wireplumber ${HOME}/.config/wireplumber

