install:
	yay -S manjaro-pipewire wireplumber helvum pipewire-pulse pipewire-alsa pipewire-jack pavuctl

link:
	ln -sf /home/Rafa/config/pipewire/config/pipewire /home/rvg/.config/pipewire
	ln -sf /home/Rafa/config/pipewire/config/wireplumber /home/rvg/.config/wireplumber

