link:
	mkdir -p ~/.local/share/applications
	ln -s -f /home/Rafa/config/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
	sudo ln -s -f /home/Rafa/config/alacritty/Alacritty.desktop /usr/share/applications/Alacritty.desktop
