link:
	mkdir -p ~/.local/share/applications
	ln -s -f /home/Rafa/config/alacritty/alacritty.desktop ~/.local/share/applications/alacritty.desktop
	ln -s -f /home/Rafa/config/alacritty/open_with_terminal_alacritty.desktop ~/.local/share/applications/open_with_terminal_alacritty.desktop
	ln -s -f /home/Rafa/config/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
