install:
	@echo "\n\n**********************************************"
	@echo "Install google chrome stable from Google's web"
	@echo "and the "Gmail Offline" chrome extension"
	@echo "**********************************************"
		
	-ln -f -s ~/Config/gmail_offline/gmail.desktop ~/.local/share/applications
	mkdir -p ~/.local/share/icons/hicolor/128x128/apps/
	cp gmail.png ~/.local/share/icons/hicolor/128x128/apps/
