all:
	sudo sed "s/Icon=.*/Icon=\/home\/Rafa\/config\/icons\/vivaldi.svg/g" -ibkp  /usr/share/applications/vivaldi-stable.desktop 
	sudo sed "s/Icon=.*/Icon=\/home\/Rafa\/config\/icons\/pd.svg/g" -ibkp  /usr/share/applications/purr-data.desktop 
	sudo sed "s/Icon=.*/Icon=gnome-terminal/g" -ibkp  /usr/share/applications/Alacritty.desktop
	sudo ln -sf  /home/Rafa/config/alacritty/Alacritty.svg /usr/share/pixmaps/Alacritty.svg
