link:
	mkdir -p ~/.local/share/applications
	ln -s -f /home/Rafa/config/key-remap/*.desktop ~/.local/share/applications
	ln -s -f /home/Rafa/config/key-remap/autokey/*.desktop ~/.local/share/applications
	ln -s -f /home/Rafa/config/key-remap/autokey ~/.config/autokey
	
	
