install:
	#yay -S neovim neovim-remote python-neovim python2-neovim xsel xclip 
	git clone https://github.com/k-takata/minpac.git ~/.config/nvim/pack/minpac/opt/minpac
	
install_more:	
	#yay -S ripgrep fd prettier yapf flake8 clang

link:
	ln -fs ~/Config/neovim/nvim ~/.config/nvim
	ln -fs ~/Config/neovim/clang-format ~/.clang-format
	echo "Do the shortcuts gnome thing! (run ./shortcuts-gnome.sh)"

