install:
	yay -S neovim neovim-remote python-neovim xsel xclip 
	#yay -S python2-neovim 
	git clone https://github.com/k-takata/minpac.git ~/.config/nvim/pack/minpac/opt/minpac
	
install_more:	
	#yay -S ripgrep fd prettier yapf flake8 clang

link:
	ln -fs ~/Config/neovim/nvim ~/.config/nvim
	ln -fs ~/Config/neovim/clang-format ~/.clang-format
	ln -fs ~/Config/neovim/php-cs-fixer.php ~/.php-cs-fixer.php

